### ISSUE TITLE
Found issues

### ISSUE THREAD

**Issue by muschellij2** [jonclayden/imbibe#1]
# drt_mean

Getting a bunch of `** nifti_set_filenames, bad params 0x0, 0x7ff62949a1d0` when trying `drt` functions

    library(imbibe)
    fname = system.file("extdata/example_4d.nii.gz", package = "RNifti")
    image = RNifti::readNifti(fname)
    image %>% drt_mean() %>% RNifti::view()
    #> beta: Using 64-bit calc
    #> Warning in run(x): nifti_image_read: failed to find header file for '#1'
    #> Error in if (any(is.na(window)) || (min == max)) {: missing value where TRUE/FALSE needed
    image %>% drt_mean() %>% run()
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    #> NULL
    fname %>% drt_mean %>% run
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    #> NULL

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-09-28                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version     date       lib source                           
    #>  assertthat    0.2.1       2019-03-21 [2] CRAN (R 4.0.0)                   
    #>  backports     1.1.10      2020-09-15 [1] CRAN (R 4.0.2)                   
    #>  callr         3.4.4       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  cli           2.0.2       2020-02-28 [2] CRAN (R 4.0.0)                   
    #>  crayon        1.3.4       2017-09-16 [2] CRAN (R 4.0.0)                   
    #>  desc          1.2.0       2020-06-01 [2] Github (muschellij2/desc@b0c374f)
    #>  devtools      2.3.1.9000  2020-08-25 [2] Github (r-lib/devtools@df619ce)  
    #>  digest        0.6.25      2020-02-23 [2] CRAN (R 4.0.0)                   
    #>  ellipsis      0.3.1       2020-05-15 [2] CRAN (R 4.0.0)                   
    #>  evaluate      0.14        2019-05-28 [2] CRAN (R 4.0.0)                   
    #>  fansi         0.4.1       2020-01-08 [2] CRAN (R 4.0.0)                   
    #>  fs            1.5.0       2020-07-31 [2] CRAN (R 4.0.2)                   
    #>  glue          1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                   
    #>  highr         0.8         2019-03-20 [2] CRAN (R 4.0.0)                   
    #>  htmltools     0.5.0       2020-06-16 [2] CRAN (R 4.0.0)                   
    #>  imbibe      * 0.1.0       2020-09-28 [1] local                            
    #>  knitr         1.29        2020-06-23 [2] CRAN (R 4.0.2)                   
    #>  lifecycle     0.2.0       2020-03-06 [2] CRAN (R 4.0.0)                   
    #>  magrittr      1.5         2014-11-22 [2] CRAN (R 4.0.0)                   
    #>  memoise       1.1.0       2017-04-21 [2] CRAN (R 4.0.0)                   
    #>  pkgbuild      1.1.0       2020-07-13 [2] CRAN (R 4.0.2)                   
    #>  pkgload       1.1.0       2020-05-29 [2] CRAN (R 4.0.0)                   
    #>  prettyunits   1.1.1       2020-01-24 [2] CRAN (R 4.0.0)                   
    #>  processx      3.4.4       2020-09-03 [1] CRAN (R 4.0.2)                   
    #>  ps            1.3.4       2020-08-11 [2] CRAN (R 4.0.2)                   
    #>  purrr         0.3.4       2020-04-17 [2] CRAN (R 4.0.0)                   
    #>  R6            2.4.1       2019-11-12 [2] CRAN (R 4.0.0)                   
    #>  Rcpp          1.0.5       2020-07-06 [2] CRAN (R 4.0.0)                   
    #>  remotes       2.2.0       2020-07-21 [2] CRAN (R 4.0.2)                   
    #>  rlang         0.4.7.9000  2020-09-09 [1] Github (r-lib/rlang@60c0151)     
    #>  rmarkdown     2.3         2020-06-18 [2] CRAN (R 4.0.0)                   
    #>  RNifti        1.2.2       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  rprojroot     1.3-2       2018-01-03 [2] CRAN (R 4.0.0)                   
    #>  sessioninfo   1.1.1       2018-11-05 [2] CRAN (R 4.0.0)                   
    #>  stringi       1.5.3       2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  stringr       1.4.0       2019-02-10 [2] CRAN (R 4.0.0)                   
    #>  testthat      2.99.0.9000 2020-09-17 [1] Github (r-lib/testthat@fbbd667)  
    #>  usethis       1.6.1.9001  2020-08-25 [2] Github (r-lib/usethis@860c1ea)   
    #>  withr         2.2.0       2020-04-20 [2] CRAN (R 4.0.0)                   
    #>  xfun          0.17        2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  yaml          2.2.1       2020-02-01 [2] CRAN (R 4.0.0)                   
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by muschellij2** [comment]
library(imbibe)
    fname = system.file("extdata/example_4d.nii.gz", package = "RNifti")
    image = RNifti::readNifti(fname)
    image %>% drt_mean() %>% run()
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    #> NULL
    image %>% drt_mean() %>% unclass()
    #> [1] "#1"     "-Tmean"
    #> attr(,"images")
    #> attr(,"images")[[1]]
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 x 3 voxels
    #> - 2.5 x 2.5 x 2.5 mm x 1 s per voxel
    fname %>% drt_mean %>% run
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    #> NULL

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-09-28                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version     date       lib source                           
    #>  assertthat    0.2.1       2019-03-21 [2] CRAN (R 4.0.0)                   
    #>  backports     1.1.10      2020-09-15 [1] CRAN (R 4.0.2)                   
    #>  callr         3.4.4       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  cli           2.0.2       2020-02-28 [2] CRAN (R 4.0.0)                   
    #>  crayon        1.3.4       2017-09-16 [2] CRAN (R 4.0.0)                   
    #>  desc          1.2.0       2020-06-01 [2] Github (muschellij2/desc@b0c374f)
    #>  devtools      2.3.1.9000  2020-08-25 [2] Github (r-lib/devtools@df619ce)  
    #>  digest        0.6.25      2020-02-23 [2] CRAN (R 4.0.0)                   
    #>  ellipsis      0.3.1       2020-05-15 [2] CRAN (R 4.0.0)                   
    #>  evaluate      0.14        2019-05-28 [2] CRAN (R 4.0.0)                   
    #>  fansi         0.4.1       2020-01-08 [2] CRAN (R 4.0.0)                   
    #>  fs            1.5.0       2020-07-31 [2] CRAN (R 4.0.2)                   
    #>  glue          1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                   
    #>  highr         0.8         2019-03-20 [2] CRAN (R 4.0.0)                   
    #>  htmltools     0.5.0       2020-06-16 [2] CRAN (R 4.0.0)                   
    #>  imbibe      * 0.1.0       2020-09-28 [1] local                            
    #>  knitr         1.29        2020-06-23 [2] CRAN (R 4.0.2)                   
    #>  lifecycle     0.2.0       2020-03-06 [2] CRAN (R 4.0.0)                   
    #>  magrittr      1.5         2014-11-22 [2] CRAN (R 4.0.0)                   
    #>  memoise       1.1.0       2017-04-21 [2] CRAN (R 4.0.0)                   
    #>  pkgbuild      1.1.0       2020-07-13 [2] CRAN (R 4.0.2)                   
    #>  pkgload       1.1.0       2020-05-29 [2] CRAN (R 4.0.0)                   
    #>  prettyunits   1.1.1       2020-01-24 [2] CRAN (R 4.0.0)                   
    #>  processx      3.4.4       2020-09-03 [1] CRAN (R 4.0.2)                   
    #>  ps            1.3.4       2020-08-11 [2] CRAN (R 4.0.2)                   
    #>  purrr         0.3.4       2020-04-17 [2] CRAN (R 4.0.0)                   
    #>  R6            2.4.1       2019-11-12 [2] CRAN (R 4.0.0)                   
    #>  Rcpp          1.0.5       2020-07-06 [2] CRAN (R 4.0.0)                   
    #>  remotes       2.2.0       2020-07-21 [2] CRAN (R 4.0.2)                   
    #>  rlang         0.4.7.9000  2020-09-09 [1] Github (r-lib/rlang@60c0151)     
    #>  rmarkdown     2.3         2020-06-18 [2] CRAN (R 4.0.0)                   
    #>  RNifti        1.2.2       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  rprojroot     1.3-2       2018-01-03 [2] CRAN (R 4.0.0)                   
    #>  sessioninfo   1.1.1       2018-11-05 [2] CRAN (R 4.0.0)                   
    #>  stringi       1.5.3       2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  stringr       1.4.0       2019-02-10 [2] CRAN (R 4.0.0)                   
    #>  testthat      2.99.0.9000 2020-09-17 [1] Github (r-lib/testthat@fbbd667)  
    #>  usethis       1.6.1.9001  2020-08-25 [2] Github (r-lib/usethis@860c1ea)   
    #>  withr         2.2.0       2020-04-20 [2] CRAN (R 4.0.0)                   
    #>  xfun          0.17        2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  yaml          2.2.1       2020-02-01 [2] CRAN (R 4.0.0)                   
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by muschellij2** [comment]
There seems to be some initialization artifact as well:

    library(imbibe)
    fname = system.file("extdata/example_4d.nii.gz", package = "RNifti")
    image = RNifti::readNifti(fname)
    out = drt_mean(image) %>% run()
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    class(out)
    #> [1] "NULL"

    minimum(image, 1) %>% 
      run()
    #> beta: Using 64-bit calc
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 x 3 voxels
    #> - 2.5 x 2.5 x 2.5 mm x 1 s per voxel

    out = drt_mean(image) %>% run()
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    class(out)
    #> [1] "internalImage" "niftiImage"

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-09-28                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version     date       lib source                           
    #>  assertthat    0.2.1       2019-03-21 [2] CRAN (R 4.0.0)                   
    #>  backports     1.1.10      2020-09-15 [1] CRAN (R 4.0.2)                   
    #>  callr         3.4.4       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  cli           2.0.2       2020-02-28 [2] CRAN (R 4.0.0)                   
    #>  crayon        1.3.4       2017-09-16 [2] CRAN (R 4.0.0)                   
    #>  desc          1.2.0       2020-06-01 [2] Github (muschellij2/desc@b0c374f)
    #>  devtools      2.3.1.9000  2020-08-25 [2] Github (r-lib/devtools@df619ce)  
    #>  digest        0.6.25      2020-02-23 [2] CRAN (R 4.0.0)                   
    #>  ellipsis      0.3.1       2020-05-15 [2] CRAN (R 4.0.0)                   
    #>  evaluate      0.14        2019-05-28 [2] CRAN (R 4.0.0)                   
    #>  fansi         0.4.1       2020-01-08 [2] CRAN (R 4.0.0)                   
    #>  fs            1.5.0       2020-07-31 [2] CRAN (R 4.0.2)                   
    #>  glue          1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                   
    #>  highr         0.8         2019-03-20 [2] CRAN (R 4.0.0)                   
    #>  htmltools     0.5.0       2020-06-16 [2] CRAN (R 4.0.0)                   
    #>  imbibe      * 0.1.0       2020-09-28 [1] local                            
    #>  knitr         1.29        2020-06-23 [2] CRAN (R 4.0.2)                   
    #>  lifecycle     0.2.0       2020-03-06 [2] CRAN (R 4.0.0)                   
    #>  magrittr      1.5         2014-11-22 [2] CRAN (R 4.0.0)                   
    #>  memoise       1.1.0       2017-04-21 [2] CRAN (R 4.0.0)                   
    #>  pkgbuild      1.1.0       2020-07-13 [2] CRAN (R 4.0.2)                   
    #>  pkgload       1.1.0       2020-05-29 [2] CRAN (R 4.0.0)                   
    #>  prettyunits   1.1.1       2020-01-24 [2] CRAN (R 4.0.0)                   
    #>  processx      3.4.4       2020-09-03 [1] CRAN (R 4.0.2)                   
    #>  ps            1.3.4       2020-08-11 [2] CRAN (R 4.0.2)                   
    #>  purrr         0.3.4       2020-04-17 [2] CRAN (R 4.0.0)                   
    #>  R6            2.4.1       2019-11-12 [2] CRAN (R 4.0.0)                   
    #>  Rcpp          1.0.5       2020-07-06 [2] CRAN (R 4.0.0)                   
    #>  remotes       2.2.0       2020-07-21 [2] CRAN (R 4.0.2)                   
    #>  rlang         0.4.7.9000  2020-09-09 [1] Github (r-lib/rlang@60c0151)     
    #>  rmarkdown     2.3         2020-06-18 [2] CRAN (R 4.0.0)                   
    #>  RNifti        1.2.2       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  rprojroot     1.3-2       2018-01-03 [2] CRAN (R 4.0.0)                   
    #>  sessioninfo   1.1.1       2018-11-05 [2] CRAN (R 4.0.0)                   
    #>  stringi       1.5.3       2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  stringr       1.4.0       2019-02-10 [2] CRAN (R 4.0.0)                   
    #>  testthat      2.99.0.9000 2020-09-17 [1] Github (r-lib/testthat@fbbd667)  
    #>  usethis       1.6.1.9001  2020-08-25 [2] Github (r-lib/usethis@860c1ea)   
    #>  withr         2.2.0       2020-04-20 [2] CRAN (R 4.0.0)                   
    #>  xfun          0.17        2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  yaml          2.2.1       2020-02-01 [2] CRAN (R 4.0.0)                   
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by muschellij2** [comment]
Same thing with threshold:

    library(imbibe)
    fname = system.file("extdata/example_4d.nii.gz", package = "RNifti")
    image = RNifti::readNifti(fname)
    image %>% threshold_above(value = 1000) %>% run()
    #> beta: Using 64-bit calc
    #> Warning in run(.): nifti_image_read: failed to find header file for '#1'
    #> NULL

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-09-28                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version     date       lib source                           
    #>  assertthat    0.2.1       2019-03-21 [2] CRAN (R 4.0.0)                   
    #>  backports     1.1.10      2020-09-15 [1] CRAN (R 4.0.2)                   
    #>  callr         3.4.4       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  cli           2.0.2       2020-02-28 [2] CRAN (R 4.0.0)                   
    #>  crayon        1.3.4       2017-09-16 [2] CRAN (R 4.0.0)                   
    #>  desc          1.2.0       2020-06-01 [2] Github (muschellij2/desc@b0c374f)
    #>  devtools      2.3.1.9000  2020-08-25 [2] Github (r-lib/devtools@df619ce)  
    #>  digest        0.6.25      2020-02-23 [2] CRAN (R 4.0.0)                   
    #>  ellipsis      0.3.1       2020-05-15 [2] CRAN (R 4.0.0)                   
    #>  evaluate      0.14        2019-05-28 [2] CRAN (R 4.0.0)                   
    #>  fansi         0.4.1       2020-01-08 [2] CRAN (R 4.0.0)                   
    #>  fs            1.5.0       2020-07-31 [2] CRAN (R 4.0.2)                   
    #>  glue          1.4.2       2020-08-27 [1] CRAN (R 4.0.2)                   
    #>  highr         0.8         2019-03-20 [2] CRAN (R 4.0.0)                   
    #>  htmltools     0.5.0       2020-06-16 [2] CRAN (R 4.0.0)                   
    #>  imbibe      * 0.1.0       2020-09-28 [1] local                            
    #>  knitr         1.29        2020-06-23 [2] CRAN (R 4.0.2)                   
    #>  lifecycle     0.2.0       2020-03-06 [2] CRAN (R 4.0.0)                   
    #>  magrittr      1.5         2014-11-22 [2] CRAN (R 4.0.0)                   
    #>  memoise       1.1.0       2017-04-21 [2] CRAN (R 4.0.0)                   
    #>  pkgbuild      1.1.0       2020-07-13 [2] CRAN (R 4.0.2)                   
    #>  pkgload       1.1.0       2020-05-29 [2] CRAN (R 4.0.0)                   
    #>  prettyunits   1.1.1       2020-01-24 [2] CRAN (R 4.0.0)                   
    #>  processx      3.4.4       2020-09-03 [1] CRAN (R 4.0.2)                   
    #>  ps            1.3.4       2020-08-11 [2] CRAN (R 4.0.2)                   
    #>  purrr         0.3.4       2020-04-17 [2] CRAN (R 4.0.0)                   
    #>  R6            2.4.1       2019-11-12 [2] CRAN (R 4.0.0)                   
    #>  Rcpp          1.0.5       2020-07-06 [2] CRAN (R 4.0.0)                   
    #>  remotes       2.2.0       2020-07-21 [2] CRAN (R 4.0.2)                   
    #>  rlang         0.4.7.9000  2020-09-09 [1] Github (r-lib/rlang@60c0151)     
    #>  rmarkdown     2.3         2020-06-18 [2] CRAN (R 4.0.0)                   
    #>  RNifti        1.2.2       2020-09-07 [1] CRAN (R 4.0.2)                   
    #>  rprojroot     1.3-2       2018-01-03 [2] CRAN (R 4.0.0)                   
    #>  sessioninfo   1.1.1       2018-11-05 [2] CRAN (R 4.0.0)                   
    #>  stringi       1.5.3       2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  stringr       1.4.0       2019-02-10 [2] CRAN (R 4.0.0)                   
    #>  testthat      2.99.0.9000 2020-09-17 [1] Github (r-lib/testthat@fbbd667)  
    #>  usethis       1.6.1.9001  2020-08-25 [2] Github (r-lib/usethis@860c1ea)   
    #>  withr         2.2.0       2020-04-20 [2] CRAN (R 4.0.0)                   
    #>  xfun          0.17        2020-09-09 [1] CRAN (R 4.0.2)                   
    #>  yaml          2.2.1       2020-02-01 [2] CRAN (R 4.0.0)                   
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by muschellij2** [comment]
Confirming these work as expected:

    library(imbibe)
    fname = system.file("extdata/example_4d.nii.gz", package = "RNifti")
    image = RNifti::readNifti(fname)
    image %>% dim_mean() %>% run()
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 voxels
    #> - 2.5 x 2.5 x 2.5 mm per voxel
    fname %>% dim_mean %>% run
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 voxels
    #> - 2.5 x 2.5 x 2.5 mm per voxel
    image %>% dim_mean() %>% unclass()
    #> [1] "#1"     "-Tmean"
    #> attr(,"images")
    #> attr(,"images")[[1]]
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 x 3 voxels
    #> - 2.5 x 2.5 x 2.5 mm x 1 s per voxel
    fname %>% dim_mean %>% run
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 voxels
    #> - 2.5 x 2.5 x 2.5 mm per voxel
    image %>% dim_mean() %>% RNifti::view()
    #> Setting window to (0, 1)

![](https://i.imgur.com/5BitGUX.png)




    out = dim_mean(image) %>% run()
    class(out)
    #> [1] "internalImage" "niftiImage"
    minimum(image, 1) %>% 
      run()
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 x 3 voxels
    #> - 2.5 x 2.5 x 2.5 mm x 1 s per voxel
    out = dim_mean(image) %>% run()
    class(out)
    #> [1] "internalImage" "niftiImage"



    image %>% threshold_above(value = 1000) %>% run()
    #> Internal image: "NIfTI image"
    #> - 96 x 96 x 60 x 3 voxels
    #> - 2.5 x 2.5 x 2.5 mm x 1 s per voxel

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Catalina 10.15.6      
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_US.UTF-8                 
    #>  ctype    en_US.UTF-8                 
    #>  tz       America/New_York            
    #>  date     2020-10-07                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib source                            
    #>  assertthat    0.2.1      2019-03-21 [2] CRAN (R 4.0.0)                    
    #>  backports     1.1.10     2020-09-15 [1] CRAN (R 4.0.2)                    
    #>  cli           2.0.2      2020-02-28 [2] CRAN (R 4.0.0)                    
    #>  crayon        1.3.4      2017-09-16 [2] CRAN (R 4.0.0)                    
    #>  curl          4.3        2019-12-02 [2] CRAN (R 4.0.0)                    
    #>  digest        0.6.25     2020-02-23 [2] CRAN (R 4.0.0)                    
    #>  ellipsis      0.3.1      2020-05-15 [2] CRAN (R 4.0.0)                    
    #>  evaluate      0.14       2019-05-28 [2] CRAN (R 4.0.0)                    
    #>  fansi         0.4.1      2020-01-08 [2] CRAN (R 4.0.0)                    
    #>  fs            1.5.0      2020-07-31 [2] CRAN (R 4.0.2)                    
    #>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                    
    #>  highr         0.8        2019-03-20 [2] CRAN (R 4.0.0)                    
    #>  htmltools     0.5.0      2020-06-16 [2] CRAN (R 4.0.0)                    
    #>  httr          1.4.2      2020-07-20 [2] CRAN (R 4.0.2)                    
    #>  imbibe      * 0.1.0      2020-10-06 [1] Github (jonclayden/imbibe@f0ffdb9)
    #>  knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  lifecycle     0.2.0      2020-03-06 [2] CRAN (R 4.0.0)                    
    #>  magrittr      1.5        2014-11-22 [2] CRAN (R 4.0.0)                    
    #>  mime          0.9        2020-02-04 [2] CRAN (R 4.0.0)                    
    #>  pillar        1.4.6      2020-07-10 [2] CRAN (R 4.0.2)                    
    #>  pkgconfig     2.0.3      2019-09-22 [2] CRAN (R 4.0.0)                    
    #>  purrr         0.3.4      2020-04-17 [2] CRAN (R 4.0.0)                    
    #>  R6            2.4.1      2019-11-12 [2] CRAN (R 4.0.0)                    
    #>  Rcpp          1.0.5      2020-07-06 [2] CRAN (R 4.0.0)                    
    #>  reprex        0.3.0.9001 2020-09-30 [1] Github (tidyverse/reprex@d3fc4b8) 
    #>  rlang         0.4.7.9000 2020-10-05 [1] Github (r-lib/rlang@0bce15a)      
    #>  rmarkdown     2.4        2020-09-30 [1] CRAN (R 4.0.2)                    
    #>  RNifti        1.2.2      2020-09-07 [1] CRAN (R 4.0.2)                    
    #>  rstudioapi    0.11       2020-02-07 [2] CRAN (R 4.0.0)                    
    #>  sessioninfo   1.1.1      2018-11-05 [2] CRAN (R 4.0.0)                    
    #>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                    
    #>  stringr       1.4.0      2019-02-10 [2] CRAN (R 4.0.0)                    
    #>  styler        1.3.2      2020-02-23 [2] CRAN (R 4.0.0)                    
    #>  tibble        3.0.3      2020-07-10 [2] CRAN (R 4.0.2)                    
    #>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)                    
    #>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)                    
    #>  xfun          0.18       2020-09-29 [1] CRAN (R 4.0.2)                    
    #>  xml2          1.3.2      2020-04-23 [2] CRAN (R 4.0.0)                    
    #>  yaml          2.2.1      2020-02-01 [2] CRAN (R 4.0.0)                    
    #> 
    #> [1] /Users/johnmuschelli/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by jonclayden** [comment]
Thanks again! I'm hoping to push an initial release to CRAN shortly, with fuller coverage of `niimath`'s options to follow later.
